# Generated by Django 5.0 on 2024-01-19 21:32

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='tag',
            name='tid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Tag Name', max_length=100),
        ),
    ]
