# Generated by Django 5.0 on 2024-01-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tag_options_tag_tid_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
    ]
