# Generated by Django 4.0 on 2024-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Brand Name', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='Second Hand', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='Model Name', max_length=100),
        ),
    ]
